name: deploy_blog
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: deply_blog
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER_NAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ${{ secrets.POSTS_PATH }}
          echo POSTS
          git pull
          echo PULL
          cd ${{ secrets.DEPLOY_PATH }}
          echo DEPLOY
          hugo
          echo hugo
        
